---
# Random Time Interval Max
rtime: 11
# Running schedule
schedule:
  continuous: false
  days_of_week:
    - Mon
    - Tue
    - Wed
    - Thu
    - Fri
  start_time: 0800
  end_time: 1800
# User authentication - experimental
ad_auth:
  use_auth: false
  user: chris
  pass: infoblox


